title = "Boilerplate"
gitRepoUrl = ""

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

organizationName = ""
projectName = ""
url = ""
baseUrl = ""
tagline = ""

[navbar]
hideableSidebar = true

[footer]
style = "dark"

[footer.links]
title = ""
copyright = "Copyright Â© 2021 [my name] Built with Moonwave and Docusaurus"
